language: scala
scala:
    - 2.11.12

script:
  - sbt nativeLink

os:
  - linux
  - osx

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: target/scala-2.11/ogl-out
  skip_cleanup: true
  on:
    branch: master
    tags: true