language: scala
scala:
    - 2.11.12

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script:
    - sbt nativeLink
    - tar --transform='flags=r;s/ogl-out/ogl/' -cvf $ARTIFACT_NAME.tar -C target/scala-2.11 ogl-out

matrix:
  include:
    - os: linux
      env: ARTIFACT_NAME=ogl-linux
    - os: osx
      env: ARTIFACT_NAME=ogl-osx

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - ogl-osx
    - ogl-linux
  skip_cleanup: true
  on:
    tags: true