language: scala
scala:
    - 2.11.12

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script:
    - sbt nativeLink
    - cp target/scala-2.11/ogl-out ogl
    - eval $ARCHIVE_SCRIPT

matrix:
  include:
    - os: linux
      env: ARCHIVE_SCRIPT='tar -cf ogl.tar ogl'
    - os: osx
      env: ARCHIVE_SCRIPT='zip ogl.zip ogl'

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - ogl-osx
    - ogl-linux
  skip_cleanup: true
  on:
    tags: true